apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - name: http
      port: 3333
      targetPort: 3333
    - name: lightship
      port: 9000
      targetPort: 9000
